### PR TITLE
Fix typo in FF_CreateIOManager issue #40

### PR DESCRIPTION
**Pull request by fnadeau**
Fix typo in FF_CreateIOManager

Description
-----------
Fix typo in API

Test Steps
-----------
Cosmetics change, no actual step to reproduce.

Checklist:
----------
- [x] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Tested on a port for PIC32 that is not part of this porject.
Tested on Linux/POSIX using test/build-combination.

Related Issue
-----------
issue #40 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by htibosch — DISMISSED** [review]
All good, thank you very much! I approve the PR.
Hein

**Comment by aggarg** [comment]
Please fix the failing formatting check.

**Comment by fnadeau** [comment]
> Please fix the failing formatting check.

main is failing too: https://github.com/FreeRTOS/Lab-Project-FreeRTOS-FAT/actions/workflows/ci.yml
see: https://github.com/FreeRTOS/Lab-Project-FreeRTOS-FAT/pull/42

Will rebase once #42  is closed.

**Comment by aggarg** [comment]
Thank you for pointing the issue with main. This has been fixed in https://github.com/FreeRTOS/Lab-Project-FreeRTOS-FAT/pull/43.

Please rebase.

**Pull request merged**
