### PR TITLE
Bugfix/zynq mount fix2

### PR DESCRIPTION
**Pull request by phelter**
Description
-----------
Fixing Mounting issues - when mounting with zynq.

Test Steps
-----------

Won't mount unless the mountFailIgnore is set.  Should this be an option/configuration?

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [x] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Note Unable to add unit tests as this needs to be tested with Zynq.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by htibosch** [comment]
Hi @phelter, this is the code where `xMountFailIgnore` is checked:
~~~
if( FF_SDDiskMount( pxDisk ) == 0 )
{
    /* _HT_ Suppose that the partition is not yet
     * formatted, it might be desirable to have a valid
     * i/o manager. */
    if( xMountFailIgnore == 0 )
    {
        FF_SDDiskDelete( pxDisk );
        pxDisk = NULL;
    }
}
~~~
So when mounting the drive fails, it is possible to keep the i/o manager and use it for formatting.

In your case, can you tell why mounting fails? Is the drive already formatted?

`xMountFailIgnore` could indeed become a configurable property.

**Comment by htibosch** [comment]
Hello @sidmodi-mw, thank you for explaining the situation.

>  on a system that has never been formatted before.

Ah yes, I recognise this problem, Let's make an option that controls `xMountFailIgnore`.

**Comment by phelter** [comment]
Thanks @htibosch ,

Would strongly lobby for: adding an init function that allows that in lieu of a precompiler defines which are very problematic for both testing and integration.

eg:
https://github.com/FreeRTOS/Lab-Project-FreeRTOS-FAT/blob/08d0cff40d9832f235442ab22e577ddf4204da52/portable/Zynq.2019.3/ff_sddisk.c#L435C1-L445 

Change to:

```

FF_Disk_t * FF_SDDiskInit( const char * pcName )
{
  return FF_SDDiskInitWithSettings(pcName, pdFALSE, 0);
}

/** 
 * Initialize  the SD Disk with configurable settings
 * @param[in] xMountFailIgnore ignore fails on mount, set to true when have systems where may not have initialized mount
 * @param[in] xDiskPartition the disk partition number to use
 */ 
FF_Disk_t * FF_SDDiskInitWithSettings( const char * pcName, BaseType_t xMountFailIgnore, BaseType_t xDiskPartition )
```

And in the header support the new declaration of the InitWithSettings() API.

**Comment by AniruddhaKanhere** [comment]
I like the approach @phelter suggested above.
Instead of making a macro/global variable, lets just create an API which can be used in lieu of the original API.

**Comment by htibosch** [comment]
@AniruddhaKanhere wrote:
> I like the approach @phelter suggested above

Me too 👍

**Comment by AniruddhaKanhere** [comment]
@htibosch and @phelter I added a PR to do what we discussed here: https://github.com/FreeRTOS/Lab-Project-FreeRTOS-FAT/pull/49.

I have not added the same API to other ports. Not sure whether we need that.
I do not have much experience with this library and will do what you folks suggest.

Let me know how would you like to proceed.

**Comment by AniruddhaKanhere** [comment]
Since PR https://github.com/FreeRTOS/Lab-Project-FreeRTOS-FAT/pull/51 has been merged which does the exact same thing as this PR, I shall close this.

Thank you for taking the time to notice, discuss and contribute to FreeRTOS+FAT @phelter and @sidmodi-mw.

**Pull request closed without merging**
